import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import LanguageSync from "../shared/components/LanguageSync";

const poppins  = Poppins(
  {
    variable: "--font-poppins",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/dashboard/flutter_bootstrap.js"
          as="script"
          type="application/javascript"
        />
         <link
          rel="preload"
          href="/dashboard/main.dart.js"
          as="script"
          type="application/javascript"
        />
      </head>
      <body
        className={` ${poppins.variable} antialiased`}
      >
        <LanguageSync />
        {children}
      </body>
    </html>
  );
}
